networks:
  1panel-network:
    external: true

services:
  vlmcsd:
    image: mikolatero/vlmcsd:latest
    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    labels:
      createdBy: Apps
    networks:
      - 1panel-network
    ports:
      - ${HOST_IP}:${PANEL_APP_PORT_HTTP}:1688
    restart: always
