networks:
  1panel-network:
    external: true
      
services:
    sun-panel:
        container_name: ${CONTAINER_NAME}
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        image: ghostchu/peerbanhelper:v7.4.15
        labels:
            createdBy: Apps
        volumes:
            - ./data:/app/data
        networks:
            - 1panel-network
        ports:
          - ${HOST_IP}:${PANEL_APP_PORT_HTTP}:9898
        environment:
          - PUID=0
          - PGID=0
          - TZ=Asia/Shanghai
        restart: always
